### ISSUE TITLE
Inferrence for direct `eval` calls is incorrect

### ISSUE THREAD

**Issue by ikarienator** [shapesecurity/shift-scope-js#18]
We should test if the `eval` identifier is globally-scoped.

**Comment by michaelficarra** [comment]
Nope, it depends on the runtime value, which we cannot guarantee.

```js
(function(){
  (function(eval){
    eval('var x = 0;');
  }(eval));
  return typeof x;
}());
```

So we are pessimistic, and assume all direct calls to a function named `eval` are direct calls to eval.
