### ISSUE TITLE
Scope unconditionally checks for's init type, even though it could be null.

### ISSUE THREAD

**Issue by tolmasky** [shapesecurity/shift-scope-js#21]
for(; index < count; ++index) { } <-- crash

line 83 is:

    if ( node.init.type === "VariableDeclaration" && init.blockScopedDeclarations.size > 0) {

should be:

    if (node.init && node.init.type === "VariableDeclaration" && init.blockScopedDeclarations.size > 0) {

**Comment by michaelficarra** [comment]
Thanks, @tolmasky! I'll take a look at this today.
