### ISSUE TITLE
"not reached" error thrown when analysing class expressions

### ISSUE THREAD

**Issue by michaelficarra** [shapesecurity/shift-scope-js#25]
Can be reproduced with `(class{});`.

**Comment by michaelficarra** [comment]
It's hitting [this line](https://github.com/shapesecurity/shift-scope-js/blob/a39809051576101c0154fdaa2837e8bfefc73ff2/src/scope-state.js#L231).

**Comment by michaelficarra** [comment]
@bakkot You probably want to make the same change [here](https://github.com/shapesecurity/shift-java/blob/48e979f7501a96eab29a6fc811e628ade2cb2028/src/main/java/com/shapesecurity/shift/scope/ScopeAnalyzer.java#L442-L446). Also, tests would be nice before closing an issue.

**Comment by bakkot** [comment]
Yeah, I'm working on it. It's possible I just have class expression names completely wrong, though, reviewing the semantics.

**Comment by bakkot** [comment]
Yeah, turns out I do. Closing this issue and opening a new one for that, which will remain open until it's tested.
