### ISSUE TITLE
little more specific document?

### ISSUE THREAD

**Issue by beatak** [shapesecurity/shift-scope-js#4]
First of all, this is great. I've been using Esprima for a while and I'm a big fan of parser to transform other JS files.  Thank you!

I'm just trying to run what it says on https://github.com/shapesecurity/shift-scope-js/blob/master/README.md but it does not seem to be working.  here's my code:

https://gist.github.com/beatak/aad8f4dc3410a241205a

The results are:

```
> % node es6.js --harmony
> import parse from "shift-parser";
> ^^^^^^
> SyntaxError: Unexpected reserved word
```

and

```
> % node es5.js --harmony
> */node_modules/shift-scope/lib/scope.js:46
>    for (var _iterator = this.variables.values()[Symbol.iterator](), _step; !(
> 
> ReferenceError: Symbol is not defined
>    at GlobalScope.Scope (*/node_modules/shift-scope/lib/scope.js:46:50)
```

Am I doing something totally off? I'm using Node v0.10.32 on Darwin Kernel Version 13.4.0/Mac OS X 10.9.5.

Thanks again!

**Comment by michaelficarra** [comment]
@beatak: #16 probably fixes this issue. Can you try out `master` and let me know if it is working for you now?

**Comment by beatak** [comment]
I tested it on my machine (xnu 13.4.0 x86_64 / node v0.10.32) and dev machine (Linux 2.6 x86_64 / node v0.10.16) and it works great. Yay to ditch 6to5-node. Thank you @michaelficarra

**Comment by michaelficarra** [comment]
Thanks for confirming.
